/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.suspectra_facematch;

import com.amazonaws.AmazonServiceException;
import com.amazonaws.SdkClientException;
import com.amazonaws.regions.Regions;
import com.amazonaws.services.rekognition.AmazonRekognition;
import com.amazonaws.services.rekognition.AmazonRekognitionClientBuilder;
import com.amazonaws.services.rekognition.model.AmazonRekognitionException;
import com.amazonaws.services.rekognition.model.FaceMatch;
import com.amazonaws.services.rekognition.model.S3Object;
import com.amazonaws.services.rekognition.model.SearchFacesByImageRequest;
import com.amazonaws.services.rekognition.model.SearchFacesByImageResult;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;
import com.amazonaws.services.s3.model.GetObjectRequest;
import com.amazonaws.services.s3.model.ObjectMetadata;
import com.amazonaws.services.s3.model.PutObjectRequest;
import com.amazonaws.services.s3.model.S3ObjectInputStream;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.awt.Graphics2D;
import java.awt.Color;
import javax.imageio.ImageIO;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.JPasswordField;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.nio.file.Paths;
import java.nio.charset.StandardCharsets;
import java.nio.file.StandardOpenOption;
import java.util.Arrays;
import java.util.Optional;


public class face_rekognition extends javax.swing.JFrame {
    
    // Store the S3 key of the uploaded sketch
    private String uploadedS3Key = null;

    public face_rekognition() {
        initComponents();
        sketch_path.setVisible(false);
        match_path.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        subtitleLabel = new javax.swing.JLabel();
        sketchPanel = new javax.swing.JPanel();
        sketchLabel = new javax.swing.JLabel();
        sketch = new javax.swing.JLabel();
        matchPanel = new javax.swing.JPanel();
        matchLabel = new javax.swing.JLabel();
        match = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        open_sketch = new javax.swing.JButton();
        upload_sketch = new javax.swing.JButton();
        find_match = new javax.swing.JButton();
        resultsPanel = new javax.swing.JPanel();
        resultsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        match_properties = new javax.swing.JTextArea();
        match_similarity = new javax.swing.JLabel();
        statusPanel = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        sketch_path = new javax.swing.JTextField();
        match_path = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Suspectra - Face Recognition System");
        setBackground(new java.awt.Color(245, 247, 250));
        setMinimumSize(new java.awt.Dimension(1200, 800));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 30, 20, 30));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(30, 58, 138));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Suspectra Face Match");

        subtitleLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        subtitleLabel.setForeground(new java.awt.Color(100, 116, 139));
        subtitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subtitleLabel.setText("AI-Powered Facial Recognition & Sketch Matching System");

        sketchPanel.setBackground(new java.awt.Color(248, 250, 252));
        sketchPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 213, 225), 2), javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)));

        sketchLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        sketchLabel.setForeground(new java.awt.Color(51, 65, 85));
        sketchLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sketchLabel.setText("Upload Sketch");

        sketch.setBackground(new java.awt.Color(255, 255, 255));
        sketch.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        sketch.setForeground(new java.awt.Color(148, 163, 184));
        sketch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sketch.setText("No image selected");
        sketch.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(226, 232, 240), 2), javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));
        sketch.setOpaque(true);

        javax.swing.GroupLayout sketchPanelLayout = new javax.swing.GroupLayout(sketchPanel);
        sketchPanel.setLayout(sketchPanelLayout);
        sketchPanelLayout.setHorizontalGroup(
            sketchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sketchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sketch, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        sketchPanelLayout.setVerticalGroup(
            sketchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sketchPanelLayout.createSequentialGroup()
                .addComponent(sketchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sketch, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
        );

        matchPanel.setBackground(new java.awt.Color(248, 250, 252));
        matchPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 213, 225), 2), javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)));

        matchLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        matchLabel.setForeground(new java.awt.Color(51, 65, 85));
        matchLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        matchLabel.setText("Matched Face");

        match.setBackground(new java.awt.Color(255, 255, 255));
        match.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        match.setForeground(new java.awt.Color(148, 163, 184));
        match.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        match.setText("No match found yet");
        match.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(226, 232, 240), 2), javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));
        match.setOpaque(true);

        javax.swing.GroupLayout matchPanelLayout = new javax.swing.GroupLayout(matchPanel);
        matchPanel.setLayout(matchPanelLayout);
        matchPanelLayout.setHorizontalGroup(
            matchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(matchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(match, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        matchPanelLayout.setVerticalGroup(
            matchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(matchPanelLayout.createSequentialGroup()
                .addComponent(matchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(match, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
        );

        buttonPanel.setBackground(new java.awt.Color(255, 255, 255));
        buttonPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 0, 10, 0));

        open_sketch.setBackground(new java.awt.Color(59, 130, 246));
        open_sketch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        open_sketch.setForeground(new java.awt.Color(255, 255, 255));
        open_sketch.setText("Open Sketch");
        open_sketch.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 24, 12, 24));
        open_sketch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        open_sketch.setFocusPainted(false);
        open_sketch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                open_sketchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                open_sketchMouseExited(evt);
            }
        });
        open_sketch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open_sketchActionPerformed(evt);
            }
        });

        upload_sketch.setBackground(new java.awt.Color(16, 185, 129));
        upload_sketch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        upload_sketch.setForeground(new java.awt.Color(255, 255, 255));
        upload_sketch.setText("Upload to AWS");
        upload_sketch.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 24, 12, 24));
        upload_sketch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        upload_sketch.setFocusPainted(false);
        upload_sketch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                upload_sketchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                upload_sketchMouseExited(evt);
            }
        });
        upload_sketch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upload_sketchActionPerformed(evt);
            }
        });

        find_match.setBackground(new java.awt.Color(139, 92, 246));
        find_match.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        find_match.setForeground(new java.awt.Color(255, 255, 255));
        find_match.setText("Find Match");
        find_match.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 24, 12, 24));
        find_match.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        find_match.setFocusPainted(false);
        find_match.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                find_matchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                find_matchMouseExited(evt);
            }
        });
        find_match.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                find_matchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(open_sketch, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(upload_sketch, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(find_match, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addContainerGap())
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(open_sketch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(upload_sketch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(find_match, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        resultsPanel.setBackground(new java.awt.Color(248, 250, 252));
        resultsPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 213, 225), 2), javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)));

        resultsLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        resultsLabel.setForeground(new java.awt.Color(51, 65, 85));
        resultsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultsLabel.setText("Match Details");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(226, 232, 240), 2));

        match_properties.setBackground(new java.awt.Color(255, 255, 255));
        match_properties.setColumns(20);
        match_properties.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        match_properties.setForeground(new java.awt.Color(71, 85, 105));
        match_properties.setRows(5);
        match_properties.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jScrollPane1.setViewportView(match_properties);

        match_similarity.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        match_similarity.setForeground(new java.awt.Color(16, 185, 129));
        match_similarity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        match_similarity.setText("Ready to match...");

        javax.swing.GroupLayout resultsPanelLayout = new javax.swing.GroupLayout(resultsPanel);
        resultsPanel.setLayout(resultsPanelLayout);
        resultsPanelLayout.setHorizontalGroup(
            resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resultsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
            .addComponent(match_similarity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        resultsPanelLayout.setVerticalGroup(
            resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultsPanelLayout.createSequentialGroup()
                .addComponent(resultsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(match_similarity, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
        );

        statusPanel.setBackground(new java.awt.Color(241, 245, 249));
        statusPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(226, 232, 240)), javax.swing.BorderFactory.createEmptyBorder(15, 20, 15, 20)));

        statusLabel.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(100, 116, 139));
        statusLabel.setText("Status: Ready | Click 'Open Sketch' to begin");

        sketch_path.setEditable(false);
        sketch_path.setBackground(new java.awt.Color(248, 250, 252));
        sketch_path.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        sketch_path.setForeground(new java.awt.Color(100, 116, 139));
        sketch_path.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 8, 5, 8));

        match_path.setEditable(false);
        match_path.setBackground(new java.awt.Color(248, 250, 252));
        match_path.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        match_path.setForeground(new java.awt.Color(100, 116, 139));
        match_path.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 8, 5, 8));

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sketch_path, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(match_path, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sketch_path, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(match_path, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(subtitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(statusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sketchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(matchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(resultsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subtitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sketchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(matchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resultsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Button hover effects
    private void open_sketchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_open_sketchMouseEntered
        open_sketch.setBackground(new java.awt.Color(37, 99, 235));
    }//GEN-LAST:event_open_sketchMouseEntered

    private void open_sketchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_open_sketchMouseExited
        open_sketch.setBackground(new java.awt.Color(59, 130, 246));
    }//GEN-LAST:event_open_sketchMouseExited

    private void upload_sketchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upload_sketchMouseEntered
        upload_sketch.setBackground(new java.awt.Color(5, 150, 105));
    }//GEN-LAST:event_upload_sketchMouseEntered

    private void upload_sketchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upload_sketchMouseExited
        upload_sketch.setBackground(new java.awt.Color(16, 185, 129));
    }//GEN-LAST:event_upload_sketchMouseExited

    private void find_matchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_find_matchMouseEntered
        find_match.setBackground(new java.awt.Color(109, 40, 217));
    }//GEN-LAST:event_find_matchMouseEntered

    private void find_matchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_find_matchMouseExited
        find_match.setBackground(new java.awt.Color(139, 92, 246));
    }//GEN-LAST:event_find_matchMouseExited

    // OPEN SKETCH AND VIEW IMAGE AND PATH
    private void open_sketchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_sketchActionPerformed
        JFileChooser fileChooser = new JFileChooser("E:\\NetBeans\\ThirdEye_FaceMatch\\src\\main\\java\\com\\mycompany\\thirdeye_facematch\\sketches"); 
        //Limit type of file name extensions supported. 
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files (*.jpg, *.png, *.jpeg, *.gif)", "jpg", "png", "jpeg", "gif"); 
        fileChooser.setFileFilter(filter); 
        int selected = fileChooser.showOpenDialog(this); 
        
        //check if open button has been clicked. 
        if (selected == JFileChooser.APPROVE_OPTION) { 
            File file = fileChooser.getSelectedFile(); 
            
            //Get Path of the selected image.
            String getselectedImage = file.getAbsolutePath(); 
            
            sketch_path.setText(getselectedImage);
                    statusLabel.setText("Status: Sketch loaded | Click 'Upload to AWS' to continue");
            
            // Clear match display when new sketch is loaded
            match.setText("No match found yet");
            match.setIcon(null);
            match_similarity.setText("Ready to match...");
            match_properties.setText("");
            match_path.setText("");
            
            try {
                ImageIcon imIco = new ImageIcon(getselectedImage);
                //make image fit on jlabel.
                Image imFit = imIco.getImage(); 
                Image imgFit = imFit.getScaledInstance(sketch.getWidth(), sketch.getHeight(), Image.SCALE_SMOOTH);
                sketch.setIcon(new ImageIcon(imgFit));
                sketch.setText(""); // Clear placeholder text
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error loading image: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }        
    }//GEN-LAST:event_open_sketchActionPerformed
    
    //UPLOAD THE SKETCH TO S3 BUCKET TO FIND A MATCH FROM AWS COLLECTION
    private void upload_sketchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upload_sketchActionPerformed
        String fileName = sketch_path.getText();

        System.out.println("[FaceMatch] Upload to AWS clicked. sketch_path='" + fileName + "'");

        // Validate that a sketch has been opened/selected first
        if (fileName == null || fileName.isBlank()) {
            JOptionPane.showMessageDialog(this, "Please open a sketch first (click 'Open Sketch').", "No Sketch Selected", JOptionPane.WARNING_MESSAGE);
                    statusLabel.setText("Status: No sketch selected | Click 'Open Sketch' first");
            return;
        }

        // Check for AWS credentials
        if (!hasAwsCredentials()) {
            if (!promptForAwsCredentials()) {
                JOptionPane.showMessageDialog(this, "AWS credentials required. Cannot upload to S3.", "AWS Credentials Required", JOptionPane.ERROR_MESSAGE);
                    statusLabel.setText("Status: Upload failed | AWS credentials required");
                return;
            }
        }

                    statusLabel.setText("Status: Uploading sketch to AWS S3...");
        
        // Clear previous match UI
        match_path.setText("");
        match.setIcon(null);
        match.setText("No match found yet");
        match_similarity.setText("Ready to match...");
        match_properties.setText("");

        try {
            // Upload sketch to S3 bucket
            String bucket = "suspectra-facematch-somzee5";
            String s3Key = "sketches/" + System.currentTimeMillis() + "_" + new File(fileName).getName();
            
                AmazonS3 s3Client = AmazonS3ClientBuilder.standard()
                    .withRegion("us-east-1") // Match your bucket region
                    .build();
            
            File sketchFile = new File(fileName);
            if (!sketchFile.exists()) {
                JOptionPane.showMessageDialog(null, "Sketch file not found: " + fileName);
                return;
            }
            
            // Upload to S3
            PutObjectRequest putRequest = new PutObjectRequest(bucket, s3Key, sketchFile);
            ObjectMetadata metadata = new ObjectMetadata();
            metadata.setContentType("image/jpeg");
            putRequest.setMetadata(metadata);
            
            s3Client.putObject(putRequest);
            System.out.println("Successfully uploaded sketch to s3://" + bucket + "/" + s3Key);
            
            // Store the S3 key for later use in FIND MATCH
            uploadedS3Key = s3Key; // Store S3 key in class variable
            
            // Also save local copy for fallback
            fallbackLocalSave(fileName);
            
                    statusLabel.setText("Status: Upload successful | Click 'Find Match' to search");
            JOptionPane.showMessageDialog(this, "Sketch uploaded successfully to AWS S3!\n\nS3 Key: " + s3Key + "\n\nNow click 'Find Match' to search the collection.", "Upload Successful", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (AmazonServiceException e) {
            System.err.println("AWS Service Error: " + e.getMessage());
            String errorMsg = "AWS Service Error: " + e.getErrorMessage() + "\nError Code: " + e.getErrorCode();
            
            // Provide helpful message for Access Denied
            if (e.getErrorCode().equals("AccessDenied")) {
                    errorMsg += "\n\nPERMISSION ISSUE:\n";
                errorMsg += "Your IAM user doesn't have permission to write to S3.\n\n";
                errorMsg += "To fix:\n";
                errorMsg += "1. Go to AWS IAM Console\n";
                errorMsg += "2. Find your IAM user\n";
                errorMsg += "3. Attach policy: AmazonS3FullAccess\n";
                errorMsg += "4. Wait 1-2 minutes, then try again\n\n";
                errorMsg += "See FIX_ACCESS_DENIED.md for details.";
            }
            
                    statusLabel.setText("Status: Upload failed | Check AWS permissions");
            JOptionPane.showMessageDialog(this, errorMsg, "AWS Service Error", JOptionPane.ERROR_MESSAGE);
        } catch (SdkClientException e) {
            System.err.println("AWS Client Error: " + e.getMessage());
                    statusLabel.setText("Status: AWS error | Falling back to local matching");
            JOptionPane.showMessageDialog(this, "AWS Client Error: " + e.getMessage() + "\n\nFalling back to local matching...", "AWS Error", JOptionPane.WARNING_MESSAGE);
            // Fallback to local matching
            String localPath = sketch_path.getText();
            if (localPath != null && !localPath.isBlank()) {
                searchLocally(localPath);
            }
        } catch (Exception e) {
            System.err.println("Unexpected error: " + e.getMessage());
            e.printStackTrace();
                    statusLabel.setText("Status: Upload failed | Error occurred");
            JOptionPane.showMessageDialog(this, "Error uploading sketch: " + e.getMessage(), "Upload Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_upload_sketchActionPerformed

    // Save a copy of the sketch locally for offline matching. Returns true on success.
    private boolean fallbackLocalSave(String srcPath) {
        if (srcPath == null || srcPath.isEmpty()) return false;
        try {
            File src = new File(srcPath);
            if (!src.exists()) return false;
            Path destDir = Paths.get("src/main/java/com/mycompany/suspectra_facematch/sketches");
            Files.createDirectories(destDir);
            Path dest = destDir.resolve("test.jpg");
            Files.copy(src.toPath(), dest, StandardCopyOption.REPLACE_EXISTING);
            // Update UI to point to local copy
            sketch_path.setText(dest.toString());
            ImageIcon imIco = new ImageIcon(dest.toString());
            Image imFit = imIco.getImage();
            Image imgFit = imFit.getScaledInstance(sketch.getWidth(), sketch.getHeight(), Image.SCALE_SMOOTH);
            sketch.setIcon(new ImageIcon(imgFit));
            return true;
        } catch (IOException ex) {
            return false;
        }
    }

    // Basic check for AWS credentials on the host so we can avoid network calls when not configured
    private boolean hasAwsCredentials() {
        String ak = System.getenv("AWS_ACCESS_KEY_ID");
        String sk = System.getenv("AWS_SECRET_ACCESS_KEY");
        if (ak != null && !ak.isEmpty() && sk != null && !sk.isEmpty()) return true;
        // Check shared credentials file for non-empty entries
        String home = System.getProperty("user.home");
        Path cred = Paths.get(home, ".aws", "credentials");
        if (Files.exists(cred)) {
            try {
                String content = Files.readString(cred, StandardCharsets.UTF_8);
                boolean hasAk = content.matches("(?s).*aws_access_key_id\\s*=\\s*\\S+.*");
                boolean hasSk = content.matches("(?s).*aws_secret_access_key\\s*=\\s*\\S+.*");
                return hasAk && hasSk;
            } catch (IOException ex) {
                return false;
            }
        }
        return false;
    }

    // Prompt user to enter AWS credentials interactively; optionally save to ~/.aws/credentials
    private boolean promptForAwsCredentials() {
        int result = JOptionPane.showConfirmDialog(null, "AWS credentials not found. Do you want to enter them now?", "AWS Credentials", JOptionPane.YES_NO_OPTION);
        if (result != JOptionPane.YES_OPTION) return false;
        String accessKey = JOptionPane.showInputDialog(null, "Enter AWS Access Key ID:");
        if (accessKey == null || accessKey.isBlank()) return false;
        JPasswordField pf = new JPasswordField();
        int ok = JOptionPane.showConfirmDialog(null, pf, "Enter AWS Secret Access Key:", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (ok != JOptionPane.OK_OPTION) return false;
        String secretKey = new String(pf.getPassword());
        if (secretKey == null || secretKey.isBlank()) return false;

        int save = JOptionPane.showConfirmDialog(null, "Save credentials to %USERPROFILE%\\.aws\\credentials for future runs?", "Save Credentials", JOptionPane.YES_NO_OPTION);
        if (save == JOptionPane.YES_OPTION) {
            try {
                Path dir = Paths.get(System.getProperty("user.home"), ".aws");
                if (!Files.exists(dir)) Files.createDirectories(dir);
                Path creds = dir.resolve("credentials");
                String content = "[default]\naws_access_key_id = " + accessKey + "\naws_secret_access_key = " + secretKey + "\n";
                Files.writeString(creds, content, StandardCharsets.UTF_8, StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Failed to write credentials file: " + ex.getMessage());
            }
        } else {
            // set system properties for this JVM run (AWS SDK can pick up system props in some cases)
            System.setProperty("aws.accessKeyId", accessKey);
            System.setProperty("aws.secretKey", secretKey);
        }
        return true;
    }

    //FIND MATCH FROM THE AWS COLLECTION AND SHOW RESULTS
    private void find_matchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_find_matchActionPerformed
        String collectionId = "suspectra_collection";
        String bucket = "suspectra-facematch-somzee5";
        
        // Get the S3 key from the uploaded sketch (stored in class variable)
        String s3Key = uploadedS3Key;
        if (s3Key == null || s3Key.isEmpty()) {
            // Fallback: try to use local test.jpg if no S3 key found
            String localPath = sketch_path.getText();
            if (localPath != null && localPath.contains("sketches") && localPath.contains("test.jpg")) {
                s3Key = "sketches/test.jpg";
            } else {
                JOptionPane.showMessageDialog(this, "Please upload the sketch to S3 first (click 'Upload to AWS').", "No Upload Found", JOptionPane.WARNING_MESSAGE);
                    statusLabel.setText("Status: No uploaded sketch | Click 'Upload to AWS' first");
                return;
            }
        }
        
                    statusLabel.setText("Status: Searching AWS Rekognition collection...");
        
        System.out.println("[FaceMatch] Searching AWS Rekognition collection: " + collectionId);
        System.out.println("[FaceMatch] Using S3 image: s3://" + bucket + "/" + s3Key);
        
        // Check for AWS credentials
        if (!hasAwsCredentials()) {
            if (!promptForAwsCredentials()) {
                JOptionPane.showMessageDialog(null, "AWS credentials required. Cannot search Rekognition collection.");
                // Fallback to local search
                searchLocally(sketch_path.getText());
                return;
            }
        }
        
        try {
                AmazonRekognition rekognitionClient = AmazonRekognitionClientBuilder.standard()
                    .withRegion("us-east-1")
                    .build();
            ObjectMapper objectMapper = new ObjectMapper();
            
            // Get an image object from S3 bucket (use the uploaded sketch)
            com.amazonaws.services.rekognition.model.Image image = new com.amazonaws.services.rekognition.model.Image()
                    .withS3Object(new S3Object()
                            .withBucket(bucket)
                            .withName(s3Key));
            
            // Search collection for faces similar to the largest face in the image.
            SearchFacesByImageRequest searchFacesByImageRequest = new SearchFacesByImageRequest()
                    .withCollectionId(collectionId)
                    .withImage(image)
                    .withFaceMatchThreshold(70F)  // Minimum 70% similarity
                    .withMaxFaces(5);  // Get top 5 matches
            
            SearchFacesByImageResult searchFacesByImageResult = 
                     rekognitionClient.searchFacesByImage(searchFacesByImageRequest);
            
            List<FaceMatch> faceImageMatches = searchFacesByImageResult.getFaceMatches();
            
            if (faceImageMatches == null || faceImageMatches.isEmpty()) {
                JOptionPane.showMessageDialog(null, "No matches found in AWS Rekognition collection.\nSimilarity threshold: 70%\n\nTrying local search as fallback...");
                // Fallback to local search
                searchLocally(sketch_path.getText());
                return;
            }
            
            // Display the best match (first in list)
            FaceMatch bestMatch = faceImageMatches.get(0);
            
            System.out.println("Found " + faceImageMatches.size() + " match(es)");
            System.out.println(objectMapper.writerWithDefaultPrettyPrinter()
                    .writeValueAsString(bestMatch));
            
            match_path.setText(bestMatch.getFace().getExternalImageId());
            
            // Display the Similarity Percentage on the Screen
            double similarity = bestMatch.getSimilarity();
            match_similarity.setText(String.format(">> %.2f%% Match", similarity));
            
            // Update similarity color based on match quality
            if (similarity >= 95.0) {
                match_similarity.setForeground(new java.awt.Color(16, 185, 129)); // Green - Excellent
            } else if (similarity >= 85.0) {
                match_similarity.setForeground(new java.awt.Color(59, 130, 246)); // Blue - Good
            } else if (similarity >= 75.0) {
                match_similarity.setForeground(new java.awt.Color(245, 158, 11)); // Orange - Fair
            } else {
                match_similarity.setForeground(new java.awt.Color(239, 68, 68)); // Red - Low
            }
            
            // Display Properties with professional formatting
            StringBuilder props = new StringBuilder();
            
            // Header Section
            props.append("+======================================================+\n");
            props.append("|       >>> MATCH FOUND - AWS REKOGNITION <<<          |\n");
            props.append("+======================================================+\n\n");
            
            // Match Quality Indicator
            String matchQuality;
            String qualityIcon;
            if (similarity >= 95.0) {
                matchQuality = "EXCELLENT";
                qualityIcon = "[**]";
            } else if (similarity >= 85.0) {
                matchQuality = "GOOD";
                qualityIcon = "[++]";
            } else if (similarity >= 75.0) {
                matchQuality = "FAIR";
                qualityIcon = "[~~]";
            } else {
                matchQuality = "LOW";
                qualityIcon = "[--]";
            }
            props.append(qualityIcon).append(" Match Quality: ").append(matchQuality).append("\n\n");
            
            // Primary Match Details
            props.append("======================================================\n");
            props.append(">>> MATCH DETAILS\n");
            props.append("======================================================\n\n");
            
            // Extract clean name from file
            String fileName = bestMatch.getFace().getExternalImageId();
            String displayName = fileName.replace(".jpg", "").replace(".jpeg", "").replace(".png", "");
            displayName = displayName.replace("-", " ").replace("_", " ");
            // Capitalize each word
            String[] words = displayName.split(" ");
            StringBuilder nameBuilder = new StringBuilder();
            for (String word : words) {
                if (!word.isEmpty()) {
                    nameBuilder.append(Character.toUpperCase(word.charAt(0)));
                    if (word.length() > 1) {
                        nameBuilder.append(word.substring(1).toLowerCase());
                    }
                    nameBuilder.append(" ");
                }
            }
            displayName = nameBuilder.toString().trim();
            
            props.append(">> Identified Person:\n");
            props.append("   ").append(displayName).append("\n\n");
            
            props.append(">> Database Reference:\n");
            props.append("   ").append(fileName).append("\n\n");
            
            props.append(">> Similarity Score:\n");
            props.append("   ").append(String.format("%.2f%%", similarity));
            props.append(" - ").append(getSimilarityBar(similarity)).append("\n\n");
            
            props.append(">> Confidence Level:\n");
            props.append("   ").append(String.format("%.2f%%", bestMatch.getFace().getConfidence()));
            props.append(" - ").append(getConfidenceBar(bestMatch.getFace().getConfidence())).append("\n\n");
            
            props.append(">> Face ID:\n");
            props.append("   ").append(bestMatch.getFace().getFaceId()).append("\n\n");
            
            // Additional matches section
            if (faceImageMatches.size() > 1) {
                props.append("======================================================\n");
                props.append(">>> ALTERNATIVE MATCHES (").append(faceImageMatches.size() - 1).append(")\n");
                props.append("======================================================\n\n");
                
                for (int i = 1; i < Math.min(faceImageMatches.size(), 4); i++) {
                    FaceMatch fm = faceImageMatches.get(i);
                    String altName = fm.getFace().getExternalImageId();
                    double altSim = fm.getSimilarity();
                    props.append(String.format("%d. %s\n", i, altName));
                    props.append(String.format("   Similarity: %.2f%% %s\n\n", altSim, getSimilarityBar(altSim)));
                }
            }
            
            // Footer
            props.append("======================================================\n");
            props.append("** Powered by AWS Rekognition\n");
            props.append("** Matched at: ").append(new java.text.SimpleDateFormat("HH:mm:ss").format(new java.util.Date())).append("\n");
            
            match_properties.setText(props.toString());
            
            // Update status
            statusLabel.setText(" Status: Match found - " + displayName + " (" + String.format("%.2f%%", similarity) + ")");
            
            // Display Matched Image from S3 using S3 client
            String matchedExternalId = bestMatch.getFace().getExternalImageId();
            System.out.println("Matched ExternalImageId: " + matchedExternalId);

            // Prepare candidate S3 keys to try (some runs store files under 'faces/' prefix)
            String[] candidates = new String[] {
                "faces/" + matchedExternalId,
                matchedExternalId,
                // try removing a leading underscore if present (sanitization variants)
                "faces/" + (matchedExternalId.startsWith("_") ? matchedExternalId.substring(1) : matchedExternalId),
                (matchedExternalId.startsWith("_") ? matchedExternalId.substring(1) : matchedExternalId)
            };

            boolean loaded = false;
            BufferedImage bufferedImage = null;
            String matchedImageKey = null;
            AmazonS3 s3Client = AmazonS3ClientBuilder.standard()
                        .withRegion(Regions.US_EAST_1)
                        .build();

            for (String candidateKey : candidates) {
                if (candidateKey == null || candidateKey.isEmpty()) continue;
                System.out.println("Trying S3 key: s3://" + bucket + "/" + candidateKey);
                try {
                    GetObjectRequest getObjectRequest = new GetObjectRequest(bucket, candidateKey);
                    com.amazonaws.services.s3.model.S3Object s3Object = s3Client.getObject(getObjectRequest);
                    S3ObjectInputStream objectInputStream = s3Object.getObjectContent();
                    bufferedImage = ImageIO.read(objectInputStream);
                    objectInputStream.close();
                    if (bufferedImage != null) {
                        System.out.println("Successfully loaded matched image: " + candidateKey);
                        loaded = true;
                        matchedImageKey = candidateKey;
                        break;
                    }
                } catch (AmazonServiceException ase) {
                    // If key not found (404), try next candidate; otherwise log and try next
                    System.err.println("AWS Service Error when trying key '" + candidateKey + "': " + ase.getMessage());
                    // continue trying other candidates
                } catch (SdkClientException sce) {
                    System.err.println("AWS Client Error when trying key '" + candidateKey + "': " + sce.getMessage());
                } catch (IOException ioe) {
                    System.err.println("IO Error reading S3 object '" + candidateKey + "': " + ioe.getMessage());
                }
            }

            if (bufferedImage != null) {
                    // Get the label dimensions (use preferred size if width/height are 0)
                    int labelWidth = match.getWidth() > 0 ? match.getWidth() : match.getPreferredSize().width;
                    int labelHeight = match.getHeight() > 0 ? match.getHeight() : match.getPreferredSize().height;
                    
                    // If still 0, use a default size
                    if (labelWidth <= 0) labelWidth = 400;
                    if (labelHeight <= 0) labelHeight = 500;
                    
                    // Scale the image to fit the label while maintaining aspect ratio
                    int imageWidth = bufferedImage.getWidth();
                    int imageHeight = bufferedImage.getHeight();
                    
                    double widthRatio = (double) labelWidth / imageWidth;
                    double heightRatio = (double) labelHeight / imageHeight;
                    double ratio = Math.min(widthRatio, heightRatio);
                    
                    int scaledWidth = (int) (imageWidth * ratio);
                    int scaledHeight = (int) (imageHeight * ratio);
                    
                    // Create scaled image
                    Image scaledImage = bufferedImage.getScaledInstance(
                        scaledWidth, 
                        scaledHeight, 
                        Image.SCALE_SMOOTH
                    );
                    
                    match.setIcon(new ImageIcon(scaledImage));
                    match.setText(""); // Clear the "No match found yet" text
                    System.out.println("Successfully loaded and displayed matched image: " + matchedImageKey);
                } else {
                    System.err.println("Failed to read image from S3: " + matchedImageKey);
                    match.setText("Failed to load image");
                    JOptionPane.showMessageDialog(null, "Could not read matched image from S3: " + matchedImageKey);
                }

        } catch (AmazonRekognitionException e) {
            System.err.println("AWS Rekognition Error: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "AWS Rekognition Error: " + e.getMessage() + "\n\nFalling back to local search...");
            // Fallback to local search
            searchLocally(sketch_path.getText());
        } catch (SdkClientException e) {
            System.err.println("AWS Client Error: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "AWS Client Error: " + e.getMessage() + "\n\nFalling back to local search...");
            // Fallback to local search
            searchLocally(sketch_path.getText());
        } catch (Exception e) {
            System.err.println("Unexpected error: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error searching for matches: " + e.getMessage());
        }
    }//GEN-LAST:event_find_matchActionPerformed

    // Helper method to create visual similarity bar
    private String getSimilarityBar(double percentage) {
        int filled = (int) (percentage / 5); // 20 segments for 0-100%
        int empty = 20 - filled;
        
        StringBuilder bar = new StringBuilder();
        bar.append("[");
        
        // Filled portion (ASCII fallback)
        for (int i = 0; i < filled; i++) {
            bar.append("#");
        }

        // Empty portion
        for (int i = 0; i < empty; i++) {
            bar.append("-");
        }
        
        bar.append("]");
        return bar.toString();
    }
    
    // Helper method to create visual confidence bar
    private String getConfidenceBar(Float percentage) {
        return getSimilarityBar(percentage.doubleValue());
    }
    
    // Local search fallback: compare the selected sketch to images in the local `faces` folder
    private void searchLocally(String sketchFilePath) {
        if (sketchFilePath == null || sketchFilePath.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please open a sketch first.");
            return;
        }

        File facesDir = new File("src/main/java/com/mycompany/suspectra_facematch/faces");
        if (!facesDir.exists() || !facesDir.isDirectory()) {
            JOptionPane.showMessageDialog(null, "Local faces directory not found: " + facesDir.getAbsolutePath());
            return;
        }

        try {
            BufferedImage sketchImg = ImageIO.read(new File(sketchFilePath));
            if (sketchImg == null) {
                JOptionPane.showMessageDialog(null, "Could not read sketch image: " + sketchFilePath);
                return;
            }

            // normalize size for comparison
            int W = 200, H = 200;
            BufferedImage s = new BufferedImage(W, H, BufferedImage.TYPE_INT_RGB);
            Graphics2D g = s.createGraphics();
            g.setColor(Color.WHITE);
            g.fillRect(0, 0, W, H);
            g.drawImage(sketchImg.getScaledInstance(W, H, Image.SCALE_SMOOTH), 0, 0, null);
            g.dispose();

            double bestScore = -1.0;
            File bestFile = null;
            BufferedImage bestImg = null;

            File[] files = facesDir.listFiles((d, name) -> {
                String ln = name.toLowerCase();
                return ln.endsWith(".jpg") || ln.endsWith(".jpeg") || ln.endsWith(".png");
            });
            if (files == null || files.length == 0) {
                JOptionPane.showMessageDialog(null, "No face images found in: " + facesDir.getAbsolutePath());
                return;
            }

            for (File f : files) {
                try {
                    BufferedImage faceImg = ImageIO.read(f);
                    if (faceImg == null) continue;
                    BufferedImage t = new BufferedImage(W, H, BufferedImage.TYPE_INT_RGB);
                    Graphics2D g2 = t.createGraphics();
                    g2.setColor(Color.WHITE);
                    g2.fillRect(0, 0, W, H);
                    g2.drawImage(faceImg.getScaledInstance(W, H, Image.SCALE_SMOOTH), 0, 0, null);
                    g2.dispose();

                    // compute mean squared error across channels
                    long sumSq = 0;
                    for (int y = 0; y < H; y++) {
                        for (int x = 0; x < W; x++) {
                            int rgb1 = s.getRGB(x, y);
                            int rgb2 = t.getRGB(x, y);
                            int r1 = (rgb1 >> 16) & 0xff;
                            int g1c = (rgb1 >> 8) & 0xff;
                            int b1 = rgb1 & 0xff;
                            int r2 = (rgb2 >> 16) & 0xff;
                            int g2c = (rgb2 >> 8) & 0xff;
                            int b2 = rgb2 & 0xff;
                            int dr = r1 - r2;
                            int dg = g1c - g2c;
                            int db = b1 - b2;
                            sumSq += dr * dr + dg * dg + db * db;
                        }
                    }
                    double mse = sumSq / (double)(W * H * 3);
                    double similarity = 100.0 * (1.0 - (mse / (255.0 * 255.0)));

                    if (similarity > bestScore) {
                        bestScore = similarity;
                        bestFile = f;
                        bestImg = faceImg;
                    }
                } catch (IOException ex) {
                    // skip file
                }
            }

            if (bestFile != null && bestScore >= 30.0) {
                match_path.setText(bestFile.getName());
                
                // Set similarity with color coding
                match_similarity.setText(String.format(">> %.2f%% Match", bestScore));
                if (bestScore >= 80.0) {
                    match_similarity.setForeground(new java.awt.Color(16, 185, 129)); // Green
                } else if (bestScore >= 60.0) {
                    match_similarity.setForeground(new java.awt.Color(59, 130, 246)); // Blue
                } else if (bestScore >= 40.0) {
                    match_similarity.setForeground(new java.awt.Color(245, 158, 11)); // Orange
                } else {
                    match_similarity.setForeground(new java.awt.Color(239, 68, 68)); // Red
                }
                
                // Professional formatting for local matches
                StringBuilder localProps = new StringBuilder();
                localProps.append("+======================================================+\n");
                localProps.append("|       >>> MATCH FOUND - LOCAL DATABASE <<<           |\n");
                localProps.append("+======================================================+\n\n");
                
                String quality = bestScore >= 80.0 ? "GOOD" : bestScore >= 60.0 ? "FAIR" : "LOW";
                String icon = bestScore >= 80.0 ? "[++]" : bestScore >= 60.0 ? "[~~]" : "[--]";
                localProps.append(icon).append(" Match Quality: ").append(quality).append("\n\n");
                
                localProps.append("======================================================\n");
                localProps.append(">>> MATCH DETAILS\n");
                localProps.append("======================================================\n\n");
                
                localProps.append(">> File Name:\n");
                localProps.append("   ").append(bestFile.getName()).append("\n\n");
                
                localProps.append(">> Similarity Score:\n");
                localProps.append("   ").append(String.format("%.2f%%", bestScore));
                localProps.append(" - ").append(getSimilarityBar(bestScore)).append("\n\n");
                
                localProps.append("======================================================\n");
                localProps.append("** Note: Local pixel-based comparison\n");
                localProps.append("** Matched at: ").append(new java.text.SimpleDateFormat("HH:mm:ss").format(new java.util.Date())).append("\n");
                
                match_properties.setText(localProps.toString());
                ImageIcon ico = new ImageIcon(bestImg.getScaledInstance(match.getWidth(), match.getHeight(), Image.SCALE_SMOOTH));
                match.setIcon(ico);
                match.setText(""); // Clear the "No match found yet" text
                statusLabel.setText(" Status: Local match found - " + bestFile.getName());
                JOptionPane.showMessageDialog(this, "Local match found: " + bestFile.getName() + " (" + String.format("%.1f", bestScore) + "%)", "Match Found", JOptionPane.INFORMATION_MESSAGE);
            } else {
                statusLabel.setText(" Status: No local match found above threshold");
                JOptionPane.showMessageDialog(this, "No local match found above 30% threshold.\n\nBest score: " + (bestScore < 0 ? "n/a" : String.format("%.1f%%", bestScore)), "No Match", JOptionPane.WARNING_MESSAGE);
                match.setIcon(null);
                match.setText("No match found");
            }

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error during local search: " + ex.getMessage());
        }
    }


    /**
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(face_rekognition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new face_rekognition().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton find_match;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel match;
    private javax.swing.JLabel matchLabel;
    private javax.swing.JPanel matchPanel;
    private javax.swing.JTextField match_path;
    private javax.swing.JTextArea match_properties;
    private javax.swing.JLabel match_similarity;
    private javax.swing.JButton open_sketch;
    private javax.swing.JPanel resultsPanel;
    private javax.swing.JLabel resultsLabel;
    private javax.swing.JLabel sketch;
    private javax.swing.JLabel sketchLabel;
    private javax.swing.JPanel sketchPanel;
    private javax.swing.JTextField sketch_path;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JLabel subtitleLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton upload_sketch;
    private javax.swing.JPanel buttonPanel;
    // End of variables declaration//GEN-END:variables
}
